### ISSUE TITLE
tpch  don't include the license file

### ISSUE THREAD

**Issue by puntogil** [trinodb/tpch#17]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by justinmclean** [comment]
How is this code licensed? From what I understand, the original code comes with these terms and conditions:
https://tpc.org/TPC_Documents_Current_Versions/source/tpc_eula.txt

Does teh same apply here?

**Comment by wendigo** [comment]
@justinmclean we are not using TPC ORG code, this is standalone generator that is based on the TPC-H specification

**Comment by justinmclean** [comment]
The maven repo says it's a port of TPC-H dbgen to Java.

**Comment by justinmclean** [comment]
And even if you based it on the original specification, it, I believe, requires you to abide by those terms.

**Comment by wendigo** [comment]
@justinmclean port of the specification, not the code
