### ISSUE TITLE
Expose TPC-H table statistics

### ISSUE THREAD

**Issue by losipiuk** [trinodb/tpch#18]
To have nice implementation of statistics interface in Presto it would be nice that table statistics
- rows count
- data size for individual columns 
  is clearly exposed by airlift-tpch. 

E.g via methods in `io.airlift.tpch.TpchTable`.

**Comment by mosabua** [comment]
Closing this issue as outdated. As far as I am aware no such feature was implemented. If you use the connector in Trino you can insert the data into an data lake with stats and use it. However having stats with the generated data would still be good .. but there is no dev effort around that from all I know.
